function getRandomDate() {
  const maxDate = Date.now();
  const timestamp = Math.floor(Math.random() * maxDate);
  return new Date(timestamp);
}

const tableData = [
  {
    id: 1,
    model: "UX9XG2",
    problem: "Screen cracked",
    category: "Mobile",
    assessDate: "08 April 2023",
    assessComplete: "08 April 2023",
    repairDate: "09 April 2023",
    repairComplete: "10 April 2023",
    status: "",
    tech: "Nicolas",
  },
  {
    id: 2,
    model: "LKRA2Q",
    problem: "Slow Phone",
    category: "Mobile",
    assessDate: "08 April 2023",
    assessComplete: "08 April 2023",
    repairDate: "09 April 2023",
    repairComplete: "10 April 2023",
    status: "",
    tech: "Jessica",
  },
  {
    id: 3,
    model: "896C1D",
    problem: "Bad Battery Life",
    category: "Mobile",
    assessDate: "08 April 2023",
    assessComplete: "08 April 2023",
    repairDate: "09 April 2023",
    repairComplete: "10 April 2023",
    status: "",
    tech: "Steven",
  },
  {
    id: 4,
    model: "DU0NSZ",
    problem: "Overheating Phone",
    category: "Mobile",
    assessDate: "08 April 2023",
    assessComplete: "08 April 2023",
    repairDate: "09 April 2023",
    repairComplete: "10 April 2023",
    status: "",
    tech: "Willard",
  },
  {
    id: 5,
    model: "95PZXE",
    problem: "App Crashes / Freezes",
    category: "Mobile",
    assessDate: "08 April 2023",
    assessComplete: "08 April 2023",
    repairDate: "09 April 2023",
    repairComplete: "10 April 2023",
    status: "",
    tech: "Kezia",
  },
  {
    id: 6,
    model: "CSE7Q0",
    problem: "Apps Not Downloading",
    category: "Mobile",
    assessDate: "08 April 2023",
    assessComplete: "08 April 2023",
    repairDate: "09 April 2023",
    repairComplete: "10 April 2023",
    status: "",
    tech: "Krish",
  },
  {
    id: 7,
    model: "1WCZ3K",
    problem: "MicroSD Card Not Working",
    assessDate: "08 April 2023",
    assessComplete: "08 April 2023",
    repairDate: "09 April 2023",
    repairComplete: "10 April 2023",
    status: "",
    tech: "Lillian",
  },
  {
    id: 8,
    model: "RX0YF5",
    problem: "Damaged Charging Port",
    category: "Mobile",
    assessDate: "08 April 2023",
    assessComplete: "08 April 2023",
    repairDate: "09 April 2023",
    repairComplete: "10 April 2023",
    status: "",
    tech: "John",
  },
  {
    id: 9,
    model: "Z9YK0C",
    problem: "Connectivity Issues",
    category: "Mobile",
    assessDate: "08 April 2023",
    assessComplete: "08 April 2023",
    repairDate: "09 April 2023",
    repairComplete: "10 April 2023",
    status: "",
    tech: "Olivier",
  },
  {
    id: 10,
    model: "FE7NSM",
    problem: "The Screen Is Not Bright Enough",
    category: "Mobile",
    assessDate: "08 April 2023",
    assessComplete: "08 April 2023",
    repairDate: "09 April 2023",
    repairComplete: "10 April 2023",
    status: "",
    tech: "Sandra",
  },
];
export { tableData, getRandomDate };
