{
    "Accessory": "",
    "ModelVersion": "0001",
    "Carrier": "",
    "CarrierName": "",
    "Dealercode": "",
    "DealerName": "",
    "DefectDesc": "door diaphragm torn -water leaking from door",
    "DisplayUnit": "",
    "RBCheck": "",
    "IMEI": "",
    "WtyType": "OW",
    "AuthNo": "",
    "Model": "WF1600W5W/XFA",
    "NewLaborWtyDate": "20161130",
    "NewPartsWtyDate": "20161130",
    "ProductDate": "20140801",
    "PurchaseDate": "00000000",
    "PurchasePlace": "",
    "Remark": "scheduled for 31/05/2023",
    "SerialNo": "0AK15ABF800015K",
    "SpecialComment": "",
    "LaborTerm": "24",
    "OtherTerm": "",
    "PartsTerm": "24",
    "WtyTermStatus": "NO",
    "WtyException": "",
    "WtyTermRemark": "Records indicate this unit is Out of Warranty.",
    "DisplayFlag": ""
}
// Return.EsModelInfo