export const unitStatus = [
    { id: 1, _status: "Booked in" },
    { id: 2, _status: "Repair in progress" },
    { id: 3, _status: "Waiting for parts" },
    { id: 4, _status: "Waiting for customer" },
    { id: 5, _status: "Parts issued" },
    { id: 6, _status: "Parts to be ordered" },
    { id: 7, _status: "Scheduled" },
    { id: 8, _status: "Customer reply" },
    { id: 9, _status: "Quality Control (QC)" },
    { id: 10, _status: "Repair complete" },
    { id: 11, _status: "Goods delivered" },
    { id: 12, _status: "Assigned to tech" },
    { id: 13, _status: "Parts request 1st approval" },
    { id: 14, _status: "Quote pending" },
    { id: 15, _status: "Quote approved" },
    { id: 16, _status: "Quote pending" },
    { id: 17, _status: "Waiting for customer" },
    { id: 18, _status: "Waiting SAW" },
    { id: 19, _status: "QC failed" },
    { id: 20, _status: "QC completed" },
    { id: 21, _status: "Pending Q&A" },
    { id: 22, _status: "SO cancel" },
    { id: 23, _status: "Scrap approved" },
    { id: 24, _status: "Quote rejected" },
    { id: 25, _status: "For invoicing" },
    { id: 26, _status: "SO cancel" },
    { id: 27, _status: "Parts DNA" },
]