CREATE TABLE service_orders (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    SERVICE_ORDER VARCHAR(10) NOT NULL UNIQUE,
    WARRANTY VARCHAR(3) NOT NULL,
    MODEL VARCHAR(20) NOT NULL UNIQUE,
    FAULT TEXT NOT NULL,
    IMEI VARCHAR(25) NOT NULL UNIQUE,
    SERIAL_NUMBER VARCHAR(30) NOT NULL UNIQUE,
    ENGINEER VARCHAR(50) NOT NULL,
    ENGINEER_ANALYSIS TEXT,
  UNIT_STATUS TEXT NOT NULL,
  ASC_CODE VARCHAR(12) NOT NULL,
  CREATED_BY TEXT,
  CREATED_DATE TEXT,
  CREATED_TIME TEXT,
  STATUS_DESC TEXT NOT NULL,
  ACCESORY TEXT, 
  PRODUCED_DATED TEXT,
  REMARK TEXT,
  WTY_TERM_REMARK TEXT,
  CUSTOMER_REQUEST_DATE TEXT,
  CUSTOMER_REQUEST_TIME TEXT,
ACKNOWLEDGE_TIME TEXT,
ACKNOWLEDGE_DATE TEXT,
COMPLETE_TIME TEXT,
COMPLETE_DATE TEXT,
ENGINEER_ASSIGNED_TIME TEXT,
ENGINEER_ASSIGNED_DATE TEXT,
FIRST_APPOINTMENT_DATE TEXT,
FIRST_APPOINTMENT_TIME TEXT,
FIRST_VISIT_TIME TEXT,
FIRST_VISIT_DATE TEXT,
FIRST_CUSTOMER_TIME TEXT,
GOODS_DELIVERY_TIME TEXT,
GOODS_DELIVERY_DATE TEXT,
LAST_APPOINTMENT_DATE TEXT,
LAST_APPOINTMENT_TIME TEXT,
LAST_CHANGE_TIME TEXT,
LAST_CHANGE_DATE TEXT,
LAST_VISIT_DATE TEXT,
LAST_VISIT_TIME TEXT,
REPAIR_RECEIVE_TIME TEXT,
REPAIR_RECEIVE_DATE TEXT,
UNIT_RECEIVE_DATE TEXT,
UNIT_RECEIVE_TIME TEXT,
CUSTOMER_FIRST_NAME TEXT,
CUSTOMER_LAST_NAME TEXT,
CUSTOMER_STREET_ADDRESS TEXT,
CUSTOMER_DISTRICT TEXT,
CUSTOMER_PROVINCE TEXT,
CUSTOMER_ZIP_CODE VARCHAR(5),
CUSTOMER_MOBILE_PHONE VARCHAR(10),
CUSTOMER_OFFICE_PHONE VARCHAR(20),
CUSTOMER_EMAIL TEXT,
CUSTOMER_CODE VARCHAR(14),
PURCHASED_DATE TEXT,
FIRST_CUSTOMER_DATE TEXT );





CREATE TABLE users (
    ID BIGSERIAL PRIMARY KEY,
    UNIQUE_ID TEXT,
    FULLNAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    CREATED_AT DATE DEFAULT CURRENT_DATE

    UNIQUE (UNIQUE_ID, EMAIL)
);

INSERT INTO service_orders (service_order) VALUES("4261942103");

DATE FORMATS
 select TO_CHAR(to_timestamp('230629', 'DDMMYY'),'YYYY-MM-DD');